### ISSUE TITLE
"cargo-vcpkg: failed" on brotli

### ISSUE THREAD

**Issue by 01joja** [mcgoo/cargo-vcpkg#17]
I have an issue where my windows 11 machine where it fails on brotli.

My cargo.toml looks like this

```Cargo
[dependencies]
specs = "0.18"
specs-derive = "0.4"

[dependencies.sdl2]
version = "0.35"
default-features = false
features = ["ttf","image","gfx","mixer","static-link","use-vcpkg"]

[package.metadata.vcpkg]
dependencies = ["sdl2", "sdl2-image[libjpeg-turbo,tiff,libwebp]", "sdl2-ttf", "sdl2-gfx", "sdl2-mixer"]
git = "https://github.com/microsoft/vcpkg"
rev = "261c458af6e3eed5d099144aff95d2b5035f656b"

[package.metadata.vcpkg.target]
x86_64-pc-windows-msvc = { triplet = "x64-windows-static-md" }
```

I added the comments from my windows 10 laptop when I installed it there.

I get following output in powershell
```powershell
PS D:\Games\Xcom_clone\xcom-clone> cargo vcpkg build
    Fetching vcpkg
    Checkout rev 261c458af6e3eed5d099144aff95d2b5035f656b
  Installing sdl2 sdl2 sdl2-image[libjpeg-turbo,tiff,libwebp] sdl2-ttf sdl2-gfx sdl2-mixer
   Compiling brotli (triplet x64-windows-static-md)
-- stdout --

-- stderr --

cargo-vcpkg: failed
```

On my windows 10 machine the `Compiling brotli (triplet x64-windows-static-md)` dosen't even show up. So I don't really understand what I'm doing wrong. Any Ideas?

**Comment by pkgw** [comment]
I usually find that when this happens, I need to update the `rev` of my vcpkg metadata — something has changed such that newer vcpkg build definitions are needed. Does that help?

From what you've written I would doubt that this has anything specifically to do with cargo-vcpkg, although surprises can definitely happen.

**Comment by joamag** [comment]
I'm also facing the same issue, I've tried to change the revision but with no success.

**Comment by waych** [comment]
Anything interesting when using the -v flag? `cargo vcpkg -v build`?

Is this cargo 0.1.7?  IIRC previous versions had a library link ordering problem that happened when brotli was pulled in.

**Comment by joamag** [comment]
I've installed pkg-config and now brotli is compiling 👍 
I'm running vcpkg on mac using an m2 pro CPU.

**Comment by Spencer1O1** [comment]
I have pkg-config installed and still getting the same issue. Did anyone find a resolution?

**Comment by Spencer1O1** [comment]
I found a solution. Make sure the revision in the metadata is a revision of a *release build*, not anything else

**Comment by Swiftloke** [comment]
To be clear, you need to go to the [vcpkg repo](https://github.com/microsoft/vcpkg) and pick out a release build. At the time of writing, the current release is [here](https://github.com/microsoft/vcpkg/releases/tag/2023.08.09) which has a revision of ``9edb1b8``. Replacing the current release revision in ``Cargo.toml`` with this one allows the build to successfully complete.
