### ISSUE TITLE
allow skipping building debug builds in vcpkg tree

### ISSUE THREAD

**Issue by mcgoo** [mcgoo/cargo-vcpkg#3]

**Comment by waych** [comment]
This is now possible using a bit of configuration on the part of the crate using cargo-vcpkg.  By specifying ones own triplet files for vcpkg, one can define and use triplets that only include either release, or debug builds as part of the triplet build. See #4 for an example.

Seeing as this sort of configuration constricts upstream builds to exclusively `debug` or `release`, it seems inappropriate to try to support the functionality directly in this crate (for loss of generality using the overlay triplet solution).
